project:
  type: website
  output-dir: docs

website:
  title: "UF Neurology Handbook"
  search: true
  repo-url: https://github.com/ufneurology/handbook
  repo-actions: [edit, source, issue]

  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Neurological Examination
        menu:
          - mental_status_exam.qmd
          - cranial_nerves.qmd
          - motor.qmd
          - sensory.qmd
          - reflexes.qmd
          - movement.qmd
          - gait_and_speech.qmd

      - text: Vascular
        menu:
          - stroke_alert.qmd
          - stroke_admission_orders.qmd
          - tia_risk_stratification.qmd
          - va_stroke_alert.qmd
          - intracerebral_hemorrhage.qmd
          - blood_pressure_pharmacology.qmd
          - anticoagulation_reversal.qmd
          - nihss_and_tools.qmd
          - modified_rankin_scale.qmd

      - text: Neurocritical Care
        menu:
          - subarachnoid_hemorrhage.qmd
          - icp_and_herniation_management.qmd
          - tbi.qmd
          - management_of_psh.qmd
          - common_critical_care_pharmacology.qmd
          - intracranial_vascular_malformation.qmd
          - common_agents_affecting_neurologic_exam.qmd
          - cardiac_arrest.qmd
          - post_anoxic_status_epilepticus.qmd
          - brain_death.qmd
          - mechanical_ventilation.qmd
          - cervical_spine_clearance.qmd

      - text: Epilepsy
        menu:
          - seizure_consult.qmd
          - status_epilepticus.qmd
          - antiseizure_medication.qmd

      - text: Neuromuscular
        menu:
          - myasthenia_gravis_exacerbation.qmd
          - guillain_barre_syndrome_aidp.qmd

      - text: Neuroimmunology
        menu:
          - multiple_sclerosis.qmd
          - optic_neuritis.qmd
          - transverse_myelitis.qmd
          - autoimmune_encephalopathy.qmd
          - neuroinfectious_disease.qmd

      - text: Neurotology
        menu:
          - dizziness_evaluation.qmd

      - text: Headache
        menu:
          - acute_headache.qmd
          - dhe_protocol.qmd
          - headache_in_pregnancy.qmd
          - idiopathic_intracranial_hypertension.qmd

      - text: Emergencies
        menu:
          - neuro_ophthalmologic_emergencies.qmd
          - parkinsons_disease_emergencies.qmd
          - other_movement_disorders_emergencies.qmd
          - neuro_oncology_emergencies.qmd

      - text: Procedures
        menu:
          - lumbar_puncture.qmd

      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true
    number-sections: true
    repo-url: https://github.com/ufneurology/handbook
    repo-actions: [edit, source, issue]

editor: visual