---
title: "Anticoagulation Reversal"
---

UF Anticoagulant reversal for intracranial hemorrhage (ICH) and other life threatening bleeding (2020)
Anticoagulant Reversal Comments
Warfarin Vitamin K 10 mg IV over 15-30 min AND FFP is not recommended with use of PCC unless
Prothrombin Complex Concentrates (PCC, otherwise indicated
eg. KCentra) 25 units/kg if INR 1.7-4, 35 Consider FEIBA in patients with a documented
units/kg if INR 4-6, or 50 u/kg if INR>6) heparin allergy as PCCs contain a small amount of
heparin
 500 units for INR ≤5
 1000 units for INR >5
Un-  1mg Protamine iv for each 100 units of Following a single bolus of heparin:
fractionated UFH. Need to consider timing and total a. Immediately: Dose 1mg protamine IV for every
heparin amount of UH administered over the last 3 100 units UFH
(UFH) hours in calculation (see next column). b. 30 min to 1 hour after a bolus: Dose 0.5 mg
 Infusion should not exceed 5mg/minute protamine IV for every 100 units UFH.
due to risk of anaphylaxis. c. >2 hours after a bolus – Dose 0.25-0.375 mg
 Maximum single dose of Protamine is 50 protamine IV for every 100 units UFH
mg, but can be repeated For continuous infusion of heparin:
Calculate dose (1 mg protamine per 100 units
UFH) for all UFH given within the last hour + one
half the dose of heparin given during the preceding
hour + one-quarter of the dose of heparin given in
the hour prior to that.
Low  1 mg Protamine IV for each 1mg of  Protamine only partially reverses the activity
molecular Enoxaparin in last 8 hours of LMWH.
weight  1 mg Protamine IV for each 100 units of  Note differences in dosing between enoxaparin
heparin Dalteparin or Tinazeparin in last 8 hours and other LMWHs
(LMWH)  For either regimen, may consider Factor  May administer 0.5 mg protamine for every 1
VIIa 45-90 mcg/kg IV for life threatening mg enoxaparin (or 100 units of dalteparin) if
intractable bleed** (Round rVIIa dose to vial LMWH dose administered 8-12 hours prior
size)  Round Factor VIIa dose to nearest 1 mg.
Factor Xa Andexanet alfa:**  Send stat anti-Xa level (LMWH). Recs may
inhibitors  Low Dose (Rivaroxaban 10 mg or less, alter depending on level
(Rivaroxaban, Apixaban 5 mg or less) (Xa inhibitor  Reversal indicated if UFH level >0.6
Apixaban, given >8h prior or dose < than 10mg):  Alternative if andexanet not available: PCC 50
Edoxaban) 400mg bolus at 30mg/min followed by IU/kg iv** or activated charcoal if Xa inhibitor
immediate infusion 4mg/min for 120 min given <8h prior
Note: (480mg total)  If no response to PCC or heparin allergy:
Andexanet  High Dose (Rivaroxaban greater than 10 -Factor VIIa 45-90 mcg/kg or FEIBA 50 units/kg
alfa not FDA mg, Apixaban greater than 5 mg) (Xa may be tried if no response to PCC
approved for inhibitor given <8h prior or dose >10mg  Note: If anti-Xa level is <0.6 there is likely
Edoxaban or dose or time unknown): 800mg bolus at little anticoagulant effect and ANY “reversal” is
reversal; 30mg/min followed by immediate infusion not necessary
requires 8mg/min for 120 min (960mg total)
attending
approval to
order
Dabigatran  Activated oral charcoal if ingestion  Consider HD, especially if renal impairment
occurred within 2 hours  If no clinical response to idarucizumab,
 Idarucizumab 5 gm IV once consider Prothrombin Complex Concentrates
(PCC) 50 units/kg**
OR
FEIBA 50 units/kg may be tried if no clinical
response to PCC or documented heparin allergy
 Note: If thrombin time and aPTT are normal
there is likely no anticoagulant effect and
“reversal” is not necessary

