# Antiseizure Medications

ANTIEPILEPTIC DRUGS

INITIAL AED CHOICE

Partial (with or without generalization) Carbamazepine, Phenytoin, most new agents

Primary Generalized Valproate, Lamotrigine, Topiramate (Phenytoin and Carbamazepine can worsen) Absence Ethosuximide, Valproate, Lamotrigine, Topiramate

AED DOSING

COMMONLY USED AEDS Seizure Type Initial dose and escalation, adults Therapeutic Level Ranges Total daily dose range, adults

(children)

Dose schedule

Carbamazepine (Tegretol, Tegretol XR, Carbatrol)

Partial onset 100mg BID, ↑ 100mg BID q3-5d

8-12 600-2400mg (15-35mg/kg) BID-QID (BID XR & Carbatrol) Felbamate (Felbatol) limited Broad spect 300mg TID, ↑ 300mg TID q7d 60-180 2400-4800mg (100-125mg/kg) BID-TID

Gabapentin (Neurontin)

Partial onset 300mg QD, ↑ 300mg QD to 300mg TID, then 300mg TID q7d

12-25 900-6000mg (20-60mg/kg) TID-QID

Lamotrigine (Lamictal) Broad spect 25mg QD, ↑ 25-50mg q2wks 10-20 100-500mg (1-5mg/kg) BID

Lamotrigine + EI-AED Broad spect 50mg QD, ↑ 50mg q2wks

300-800mg (5-15mg/kg) BID

Lamotrigine + VPA Broad spect 25mg QOD, ↑ 25mg q2wks

100-300mg (0.5-2mg/kg) QD-BID

Levetiracetam (Keppra) Broad spectrum 250mg BID, ↑ 250-500mg BID qwk 20-40 1000-4000mg (30-100mg/kg) BID

Oxcarbazepine (Trileptal) Partial onset 150mg BID, ↑ 150-300mg BID qwk 12-35 900-2400mg (20-50mg/kg) BID-TID

Phenobarbital (Luminal) Partial onset 30-60mg QD, ↑ 30-60mg q1-2wk 20-40 60-240mg (4-8mg/kg) QD-BID

Phenytoin (Dilantin)

Partial onset 200-300mg QD (Oral load 6-7mg/kg q8h x 3 doses)

10-20 total (1.0-2.0 free) 200-500mg (4-8mg/kg) QD-BID

Pregabalin (Lyrica) Partial onset 50-100mg BID ↑ 50-100mg BID qwk

150-600mg BID-TID

Tiagabine (Gabitril)

4mg QD, ↑ 4-8mg  BID-TID qwk

32-56mg (0.1-0.4mg/kg) BID-TID

Topiramate (Topamax) Broad spect 25-50mg QD, ↑ 25mg BID

q1-2wk

8-25 100-600mg (5-15mg/kg) BID

Valproate (Depakote,) Broad spect 125-250mg BID, ↑ 125-250mg BID qwk 60-120 1000-4000mg (15-60mg/kg) BID-TID (QD
- ER) Rufinamide (Banzel) Broad spec (LGS) 200 to 400 mg BID, ↑400 to 800mg/day q2 days

1600-3200mg BID

Lacosamide (Vimpat) Partial Onset 50mg BID, ↑by 100mg per day qweek

200-400mg BID

Zonisamide (Zonegran) Broad spect 100-200mg QD, ↑ 100-200mg QD Qwk

20-30 200-600mg (8-12mg/kg) QD-BID

Perampanel (Fycompa) Partial Onset 2-4mg QHS, ↑ 2mg QD Q 2wks

2mg-12mg QD

Clobazam (Onfi) Broad Spect (LGS, esp) 5mg QD x 2 wks, then BID ↑ 5mg QD Qwk

5mg QD – 40mg BID

Eslicarbazepine (Aptiom) Partial onset 400mg daily x 1 week; may ↑ 400mg daily Qwk

400mg-1200mg QD

AED SIDE EFFECTS AND INTERACTIONS

Medication Side Effects Interaction Carbamazepine (CBZ) Diplopia, blurred vision, lethargy, liver failure, SIADH, aplastic anemia

PHT, PB, VPA – decrease levels Diltiazem, verapamil, cephalosporins, antifungals – increase levels Gabapentin (GPN) Lethargy, ataxia, weight gain None

Levetiracetam (LEV) Lethargy, dizziness, depression, psychosis None

Lamotrigine (LMG or LTG) Insomnia, rash (severe) PHT, PB, OCPs – decrease levels VPA – increase levels Oxcarbazepine (OXC) Hyponatremia, nausea, rash CBZ, PB, PHT, VPA, verapamil – decrease levels Phenobarbital (PB) Lethargy, sedation, depression VPA

Phenytoin (PHT or DPH) Nausea/vomiting, dizziness, sedation, ataxia, gingival hyperplasia, liver failure, osteoporosis

CBZ, PB – decrease levels VPA – increase levels Decrease OCP effectiveness

Topiramate (TOP or TPM) Cognitive impairment, dizziness, metabolic acidosis, kidney stones, hypohidrosis

PHT, CBZ, VPA – decrease levels Decrease OCP effectiveness

Valproic Acid (VPA) Weight gain, hepatotoxicity, hyperammonemia, tremor, rash PHT, PB, TOP, CBZ – decrease levels Elavil – increase levels Zonisamide (ZNS) Sedation, rash, kidney stones, hypohidrosis PHT, CBZ, PB – decrease levels

