---
title: "Brain Death"
category: "Neurocritical Care"
format: html
editor: visual
---

# Determination of Brain Death

## Prerequisites (all must be checked)

- [ ] Coma, irreversible and cause known  
- [ ] Neuroimaging explains coma  
- [ ] CNS depressant drug effect absent (if indicated toxicology screen; if barbiturates given, serum level < 10 μg/mL)  
- [ ] No evidence of residual paralytics (electrical stimulation if paralytics used)  
- [ ] Absence of severe acid-base, electrolyte, endocrine abnormality  
- [ ] Normothermia or mild hypothermia (core temp > 36°C)  
- [ ] Systolic BP ≥ 100 mm Hg  
- [ ] No spontaneous respirations  

## Examination (all must be checked)

- [ ] Pupils nonreactive to bright light  
- [ ] Corneal reflex absent  
- [ ] OCR absent (only test if C spine integrity ensured)  
- [ ] Oculovestibular reflex absent  
- [ ] No facial movement to noxious stimuli at supraorbital nerve, TMJ  
- [ ] Gag reflex absent  
- [ ] Cough reflex absent to tracheal suctioning  
- [ ] Absence of motor response to noxious stimuli in all four limbs (spinally mediated reflexes permissible)  

## Apnea Testing (all must be checked)

- [ ] Pt is hemodynamically stable  
- [ ] Ventilator adjusted to provide normocarbia (PaCO₂ 35–45 mm Hg)  
- [ ] Patient preoxygenated with 100% FiO₂ for >10 minutes to PaO₂ >200 mm Hg  
- [ ] Patient well-oxygenated with a positive end-expiratory pressure (PEEP) of 5 cm of water.  
- [ ] Provide oxygen via a suction catheter to the level of the carina at 6 L/min or attach T-piece with continuous positive airway pressure (CPAP) at 10 cm H₂O.  
- [ ] Disconnect ventilator  
- [ ] Spontaneous respirations absent  
- [ ] Arterial blood gas drawn at 8–10 minutes, patient reconnected to ventilator  
- [ ] PaCO₂ ≥60 mm Hg, or 20 mm Hg rise from normal baseline value.  

**OR**

- [ ] Apnea test aborted  

## Ancillary Testing

To be performed only if clinical examination cannot be performed due to patient factors, or if apnea testing inconclusive or aborted. Only one needs to be performed.

- Cerebral angiogram  
- HMPAO Spect  
- EEG  
- TCD  

- [ ] Document time of death (i.e. time of apnea confirmed by diagnostic ABG, or result of ancillary test if applicable)

---