---
title: "Guillain Barre Syndrome (AIDP)"
---

GUILLAIN-BARRÉ SYNDROME (AIDP)
 History and exam
o Recent infections – Post-vaccination, C. jejuni, flu, CMV, EBV, mycoplasma
o Symptoms develop over days, can be asymmetric
o Look for weakness (most often without sensory loss) in distal>proximal, loss of reflexes
(though can be normal early)
o Back pain is common, and can be sign of demyelinating radiculitis
o Incidence of GBS will increase with age, age>50 are at higher risk for GBS
 Admission orders
o Depending on respiratory status, consider IMC versus ICU admission.
o Address code status in the ED as the patient may need intubation.
o Check NIF and FVC q2h x 12 h then q4h. Consider intubation if NIF < 20 or FVC < 15cc/kg
(or 1 liter) or a rapid downward trend is observed.
o Consider intubation:
-20/30/40 rule: VC <20ml.kg (or 1 liter); MIP<30, MEP <40. Reduction in VC, MIP, MEP
>30%,
PO2 <70 mmHg on room air,
PCO2 >50 mmHg w.acidosis
o Order telemetry – high risk of tachyarrhythmias from autonomic instability.
o Aggressive bowel regimen, close monitoring for toxic megacolon or aspiration (autonomic
involvement)
o Avoid beta-blockers because there is a risk of complete heart block.
o Perform a bedside swallow to evaluate for aspiration risk
o Order DVT prophylaxis including SCDs
 Work-up
o Perform a lumbar puncture. There should be albumino-cytological dissociation (protein much
higher than cells). Can be normal if caught early
o Check HIV, CMV, hepatitis panel, and Campylobacter in stool
o Order an EMG/NCS - look for absence or prolonged ‘F’ waves or H-reflexes, conduction
block, and temporal dispersion (but not always early in the disease!)
 Treatment
o IVIg 2 grams/kg divided in 4-5 days.
o Check IgA level prior to administration of IVIg as it may cause anaphylaxis in patients with
IgA deficiency. Give Acetaminophen and Benadryl prior to each IVIg.
Peripheral neuropathies: EMG/NCS may help guide you
 Sensory-Motor polyneuropathy: HbA1c, TSH, BUN/Cr, RPR, B12, ANA, ANCAs, Lyme, LFTs, SPEP,
UPEP, SSA/B, RF, ESR, HIV, consider heavy metal screen (needs special navy blue top tube)
 Sensory neuropathy: SSA/B, anti-Hu
 Mononeuritis multiplex: HbA1c, Lyme ab, SPEP/UPEP, ANA, ANCA, ESR, RPR, HIV, hepatitis
serologies, consider cryoglobulins
Polyneuropathy and mononeuritis multiplex: not sure how to start your differential?
Acute AIDP (GBS), AMAN (very fast, axonal motor-only GBS), vasculitis, porphyria, toxins
(organophosphates, arsenic, thalidomide), tick, drugs, acute thiamine deficiency, critical
care neuropathy
Stepwise Vasculitis: PAN, Sjogren, Churg-Strauss, Wegener's, hypersensitivity cryoglobulinemia,
(mononeuritis) SLE, RA, isolated PNS vasculitis. DM. CIDP. Infectious: Lyme, HIV, HepC/ cryos,
leprosy. Infiltration: (sarcoid (esp. b/l facial nerve), granuloma, leukemia/lymphoma)
Predom motor lead, porphyria, hereditary, AIDP/CIDP, multifocal motor neuropathy (MMN),
dysproteinemia
Pure sensory paraneoplastic (anti-Hu), Sjogren, toxic (cisplatin, B6), HIV, anti-sulfatide Ab,
Friedreich's, idiopathic, hereditary (HSN)
Predom autonomic AIDP, DM, amyloid
* toxins concentrated in urine can affect the bladder worst (e.g. cisplatin)
Small-fiber DM, amyloid, toxic (EtOH), hereditary, Tangier, Fabry, AIDS, idiopathic
Demyelinating Acute: AIDP; Sub-acute: CIDP, lead, POEMs; Chronic: CIDP, CMT1, HNPP

