---
title: "Guillain-Barré Syndrome (AIDP)"
category: "Neuromuscular"
section_id: "guillain-barre"
last_updated: "2026-07-01"
source: "UF Neurology Resident Handbook 2026-2027"
---

# Guillain-Barré Syndrome (AIDP)

Guillain-Barré Syndrome (AIDP)

History and exam

- Recent infections – Post-vaccination, C. jejuni, flu, CMV, EBV, mycoplasma

- Symptoms develop over days, can be asymmetric

- Look for weakness (most often without sensory loss) in distal>proximal, loss of reflexes (though can be normal early)

- Back pain is common, and can be sign of demyelinating radiculitis

- Incidence of GBS will increase with age, age>50 are at higher risk for GBS

Admission orders

- Depending on respiratory status, consider IMC versus ICU admission.

- Address code status in the ED as the patient may need intubation.

- Check NIF and FVC q2h x 12 h then q4h. Consider intubation if NIF < 20 or FVC < 15cc/kg (or 1 liter) or a rapid downward trend is observed.

- Consider intubation:

- -20/30/40 rule: VC <20ml.kg (or 1 liter); MIP<30, MEP <40. Reduction in VC, MIP, MEP >30%,

- PO2 <70 mmHg on room air,

- PCO2 >50 mmHg w.acidosis

- Order telemetry – high risk of tachyarrhythmias from autonomic instability.

- Aggressive bowel regimen, close monitoring for toxic megacolon or aspiration (autonomic involvement)

- Avoid beta-blockers because there is a risk of complete heart block.

- Perform a bedside swallow to evaluate for aspiration risk

- Order DVT prophylaxis including SCDs

Work-up

- Perform a lumbar puncture.  There should be albumino-cytological dissociation (protein much higher than cells). Can be normal if caught early

- Check HIV, CMV, hepatitis panel, and Campylobacter in stool

- Order an EMG/NCS - look for absence or prolonged ‘F’ waves or H-reflexes, conduction block, and temporal dispersion (but not always early in the disease!)

Treatment

- IVIg 2 grams/kg divided in 4-5 days.

- Check IgA level prior to administration of IVIg as it may cause anaphylaxis in patients with IgA deficiency. Give Acetaminophen and Benadryl prior to each IVIg.

	Peripheral neuropathies: EMG/NCS may help guide you

- Sensory-Motor polyneuropathy: HbA1c, TSH, BUN/Cr, RPR, B12, ANA, ANCAs, Lyme, LFTs, SPEP, UPEP, SSA/B, RF, ESR, HIV, consider heavy metal screen (needs special navy blue top tube)

- Sensory neuropathy: SSA/B, anti-Hu

- Mononeuritis multiplex: HbA1c, Lyme ab, SPEP/UPEP, ANA, ANCA, ESR, RPR, HIV, hepatitis serologies, consider cryoglobulins

Polyneuropathy and mononeuritis multiplex: not sure how to start your differential?

| Acute | AIDP (GBS), AMAN (very fast, axonal motor-only GBS), vasculitis, porphyria, toxins (organophosphates, arsenic, thalidomide), tick, drugs, acute thiamine deficiency, critical care neuropathy |
| --- | --- |
| Stepwise (mononeuritis) | **Vasculitis**: PAN, Sjogren, Churg-Strauss, Wegener's, hypersensitivity cryoglobulinemia, SLE, RA, isolated PNS vasculitis. **DM****. ****CIDP****.** **Infectious**: Lyme, HIV, HepC/ cryos, leprosy. **Infiltration**: (sarcoid (esp. b/l facial nerve), granuloma, leukemia/lymphoma) |
| Predom motor | lead, porphyria, hereditary, AIDP/CIDP, multifocal motor neuropathy (MMN), dysproteinemia |
| Pure sensory | paraneoplastic (anti-Hu), Sjogren, toxic (cisplatin, B6), HIV, anti-sulfatide Ab, Friedreich's, idiopathic, hereditary (HSN) |
| Predom autonomic | AIDP, DM, amyloid * toxins concentrated in urine can affect the bladder worst (e.g. cisplatin) |
| Small-fiber | DM, amyloid, toxic (EtOH), hereditary, Tangier, Fabry, AIDS, idiopathic |
| Demyelinating | Acute: AIDP; Sub-acute: CIDP, lead, POEMs; Chronic: CIDP, CMT1, HNPP |