---
title: "Lower Extremity Strength Testing"
---

Lower Extremity Strength Testing
Nerve
Action Muscles Nerves
Roots
Femoral nerve, and L1- L1, L2,
Hip flexion Iliopsoas
L3 nerve roots L3, L4
Knee extension Quadriceps Femoral nerve L2, L3, L4
Hamstrings (semitendinosus,
Knee flexion Sciatic nerve L5, S1, S2
semimembranosus, biceps femoris)
Gluteus medius, Gluteus minimus, Tensor
Leg abduction Superior gluteal nerve L4, L5, S1
fasciae latae
Obturator externus, Adductor longus,
Leg adduction Obturator nerve L2, L3, L4
magnus, and brevis, Gracilis
Toe Extensor hallucis longus, Extensor
Deep peroneal nerve L5, S1
dorsiflexion digitorum longus
Foot
Tibialis anterior Deep peroneal nerve L4, L5
dorsiflexion
Foot plantar
Triceps surae (gastrocnemius, soleus) Tibial nerve S1, S2
flexion
Superficial peroneal
Foot eversion Peroneus longus, Peroneus brevis L5, S1
nerve
Foot inversion Tibalis posterior Tibal nerve L4, L5
Segmental Reflex Innervation:
Muscle Primary Nerve Root
Biceps C6
Triceps C7
Brachioradialis C6
Knee L4
Ankle S1

