---
title: "Neurocritical Care"
---

NEUROCRITICAL CARE
Intracranial Vascular Malformations
Vascular Malformation Rupture Risk and Suggested Treatment
Type Yearly Risk Factors Treatment
rupture risk
AVM 5% Size (>3 cm), deep venous Surgical, gamma knife embolization,
drainage, nidal aneurysms, observation depending on location, size,
prior hemorrhage age
Cavernous 2-3% Prior hemorrhage Surgical vs observation
malformation
Venous angioma 0.1-0.5% Large size Not warranted
Capillary Unknown -- Not warranted
telangiectasia (rare)
Subarachnoid hemorrhage
Thunderclap SAH, pituitary apoplexy, arterial dissection, venous sinus thrombosis, hypertensive
headache ddx urgency, RCVS, intracranial hypotension, primary thunderclap headache
Sulcal subarachnoid RCVS, venous sinus thrombosis, vasculitis, mycotic aneurysm, trauma, amyloid
hemorrhage ddx angiopathy, meningeal neoplasm, dural AV fistula, meningitis
Immediate Management in the ED
To conform the diagnosis:
 Non-contrast CT
 LP if CT findings are normal (xanthochromia might be falsely negative if <6h from symptom onset)
Follow up Management after confirmed SAH
 Obtain CBC, electrolytes, Ca, Mg, PT/PTT, glucose
 ECG and CXR to rule out neurogenic pulmonary edema or cardiac stunning
 Keep SBP <160 mm Hg until aneurysm secured. Use labetalol 10 mg IV if HR >60, hydralazine 10
mg IV for HR <60
 Neurosurgery consultation for angiography and/or EVD
 EVD if patient has depressed LOC and hydrocephalus
 Tranexamic acid 1 g IV if onset within past 72 hours; caution in patients with severe coronary artery
 disease or who have a delayed presentation and may already be in vasospasm
 Monitor for complications: rebleeding, hydrocephalus, vasospasm and hyponatremia due to cerebral
salt wasting or SIADH
 Call NICU consultant, admit to ICU
 Bedside dysphagia evaluation to be performed by admitting resident. NPO if fails
o Consider formal SLP assessment if facial weakness/significant dysarthria
o No oral meds prior to bedside dysphagia screen
Admission Orders
1. Include WFNS, Modified Fisher, Hunt and Hess scores in initial note (See tables below)
2. Admit to NICU unit 47 under neurosurgery service
3. Neuro checks per unit routine
4. Order STAT head CT if neurologic deterioration.
5. Blood pressure management: Labetalol 10 mg, every 15 minutes if HR >60, alternatively use
hydralazine 10 mg for HR <60. For refractory HTN, initiate nicardipine infusion and titrate to effect.
a. Unsecured aneurysm, keep SBP <160 mm Hg
b. Consider inserting arterial line for dynamic monitoring
6. Continue TXA 1g q6h until aneurysm is secured (no more than 72h); caution in pts with severe
cardiac disease
7. Nimodipine 60 mg every 4 hours by mouth or NG tube for 21 days for delayed cerebral ischemia
prophylaxis. Transition to 30 mg q2h if patient develops hypotension with typical dosing.
8. Monitor for elevated intracranial pressure
9. Discuss management with NCCM fellow and neurosurgery
10. Strict bedrest and strict I/Os, insert urinary catheter
11. Daily electrolytes to monitor for hyponatremia

