---
title: "Neuroimmunology"
---

MS EXACERBATION (FLARE)
Epi: expect 1-2 flares in untreated RRMS patient per year (75% will have at least 1 flare)
Presentation:
Relapse: patient-reported or objectively observed events typical of an acute inflammatory demyelinating event in
the CNS current or historical, with duration of at least 24 hours, in the absence of fever or infection. Consider:
vision loss with painful eye movements (optic neuritis), trigeminal neuralgia, focal weakness, focal numbness,
ataxia, parasthesias, incontinence, falls, fatigue. KEY WORDS: NEW or WORSE; 24 hours or more; Symptom
MUST be associated with FINDING on exam
Pseudorelapse: acute worsening of symptoms that is typically associated with an increase in body temperature,
which can be due to infection, exercise, or heat exposure.
HISTORY:
 Current symptoms (onset, duration, progression)
 Past neurologic symptoms (if MS suspected)
 Recent signs of infection (fever, chills, URI symptoms, dysuria)
 If patient has known MS, have they ever had these exact symptoms before? This may suggest
recrudescence due to systemic issue, such as an infection
 Pregnancy
If known MS, MS history:
 When, where, and how they were diagnosed
 Type of MS (RRMS, PPMS, SPMS, NMO)
 Medication history and compliance, if on Tysabri, Gilenya or Tecfidera: LAST JCV TEST result
 Last exacerbation, last round of steroids
 If on Tysabri, date of last infusion. Watch out for Tysabri discontinuation rebound (usually around 3
months from last infusion)
 Baseline deficits
EXAM:
Full physical and neurologic exam with specific attention to APD, optic nerve pallor, INO, Lhermitte’s sign,
spasticity, and hyper-reflexia
Workup +/- Admission + Treatment:
1) Rule out infection with UA/Ucx & CXR if indicated. If positive, may represent a “pseudoexacerbation” - treat
the infection first and see if flare resolves. Patient may also warrant admission to medical service.
2) Rule out Uhtoff's phenomenon (unmasking of old flare symptoms due to increased body temperature) - may
not warrant acute steroid administration.
3) Consider admission based on following criteria – “can’t see” (optic neuritis), “can’t pee” (myelitis,
neurogenic bladder), “can’t eat/swallow,” “can’t walk,” or “can’t take care of family.” If not admitted, can
arrange outpatient infusion center IV steroids. Should also admit for first-time receiving IV steroids to monitor
for paradoxical (psychiatric) reaction.
4) Start IV Solumedrol 1 g/d x 3-5 days. No need for oral taper if 5 days or less.
5) Prevent steroid side effects with GI prophylaxis (ranitidine 150 bid), finger stick glucose checks/sliding scale
insulin, diabetic diet, and mental status checks. Consider a sleep aid.
6) Order PT/OT/Rehab service consults immediately if patient is unable to care for self at home on admission.
7) Continue outpatient symptomatic medications, such as muscle relaxants, SSRIs, stimulants, anticonvulsants,
antipsychotics, amantadine, etc. Immunomodulating therapies (Interferons, Glatiramer acetate, Gilenya,
Tecfidera, Aubagio) can be continued using home supply.
Evidence for treatment in acute MS exacerbations
 IV steroids may expedite the timing of recovery from a flare
 IV steroids will not increase the degree of recovery or the course of disease
 High-dose oral steroids may also expedite recovery, but IV treatment remains standard
 Alternatives to failed IV steroids include IVIG and plasma exchange
If suspected new diagnosis:
 A full differential needs to be considered. Work-up: MRI brain and spine w/wo contrast, ACE (sarcoidosis),
Lyme disease, anti-NMO Ab, RPR/VDRL, vasculitis and autoimmune panel, and lumbar puncture. CSF should
be evaluated for CSF for basic studies and oligoclonal bands, myelin basic protein, IgG index, Lyme, ACE.

