# Neuroleptic Malignant Syndrome, Serotonin Syndrome, and Acute Dystonia

NEUROLEPTIC MALIGNANT SYNDROME (NMS)

Signs and symptoms
1. Mental status change: agitated delirium, confusion, encephalopathy (82%)
2. Muscular rigidity: “lead pipe” tremor (up to 92%)  elevated CPK and myoglobinuric acute renal failure
3. Hyperthermia: >38°C (87%), >40°C (40%)
4. Autonomic instability: tachycardia (88%), labile BP (77%), tachypnea (73%), diaphoresis

Diagnosis
1. Exclude other etiologies: acute drug intoxication, metabolic derangements, meningitis, etc.

Treatment
1. Admit to ICU
2. Discontinue offending agent (e.g. neuroleptics, D2 blocking antiemetics or abrupt w/d levodopa)
3. Supportive care for Autonomic instability, DVT/PE prophylaxis, IVFs to prevent rhabdo
4. Symptomatic treatment: a. Agitation
- Lorazepam 0.5-1mg prn (may also help with rigidity) b. Rigidity – Dantrolene 0.25-2mg/kg IV q6-12 hours (max dose 10mg/kg/day; be aware of hepatotoxicity) c. Fever – cooling blankets, ice lavage, acetaminophen

SEROTONIN SYNDROME (SS)

Signs and symptoms
1. Mental status change: agitated delirium, restlessness, disorientation
2. Neuromuscular hyperreactivity: tremor, rigidity, myoclonus, rigidity, hyperreflexia (+Babinski and clonus)
3. Autonomic instability: dilated pupils, diaphoresis, hypertension, diarrhea, vomiting

Diagnosis
1. Exclude other etiologies: acute drug intoxication, metabolic derangements, meningitis, etc.

Treatment
1. Admit to ICU
2. Discontinue offending agent (e.g. SSRIs, MAOIs, buspirone, trazodone, lithium, opiates, etc.)
3. Supportive care for Autonomic instability, DVT/PE prophylaxis
4. Symptomatic treatment:

a. Agitation, Neuromuscular hyperreactivity
- Lorazepam 0.5-1mg prn b. Cyptoheptadine (only for severe cases) 12 mg PO, then 2mg q2 hours until clinical response

ACUTE DYSTONIC REACTION

Signs and symptoms
1. Intermittent or sustained dystonic posturing due to blockade of D2 receptor (neuroleptics, certain antiemetics)

Diagnosis
1. Review medication list/MAR for offending agent.
2. Exclude metabolic derangements (hypomagnesemia, hypocalcemia) or other drug toxicity.

Treatment
1. Discontinue offending agent
2. Diphenhydramine 25-50mg IV/IM vs Lorazepam 0.5-1mg IV (acute); Diphenhydramine 25mg PO qid (x48hr)
3. Alternative therapy: Benztropine 2mg IV/IM (acute); Benztropine 1-2mg PO bid (x48hr)

Neuro-oncology Emergencies

Common Medical Complications of Brain Tumors

Brain tumor

Direct effects
- Epilepsy
- Stroke
- SIADH
- Diabetes insipidus
- Behavioral symptoms

Indirect effects
- VTE
- Stroke

Iatrogenic causes

Surgery
- Stroke
- Cerebral abscess

Chemotherapy
- Nausea, vomiting
- Constipation
- HTN
- Stroke
- PRES
- Bowel perforation
- Myelotoxicity

Radiation
- Fatigue
- Dermatitis
- Memory loss
- Hearing loss
- Cataracts

Steroids
- Cushing syndrome
- Infection
- Diabetes mellitus
- Mood disorder
- Myopathy
- Tremor

AEDs
- Sedation
- Fatigue
- Irritability
- Hyponatremia
- Tremor
- Rash
- Myelotoxicity

Antineoplastic therapies Supportive therapies

Mass effect

Neuro- onc specifics

- Vasogenic edema: tumor increases vascular permeability responds to steroids
- If new lesion and suspicious for CNS lymphoma, consider osmotic therapy as a bridge to urgent biopsy as dexamethasone can decrease yield of biopsy

Acute tx

- Use lowest effective dose of dexamethasone: typically 4 mg BID sufficient – attempt to taper to lowest dose that does not cause return of substantive deficits that impair function
- Schedule at 6 am and 2 pm to avoid insomnia

Other
- Select patients (ie. large contrast enhancing tumors with significant vasogenic edema) may benefit from bevacizumab long term as can improve edema over days to weeks

Herniation Acute tx
- If obtunded or herniation: Dexamethasone 10 mg IV once, then 4 mg q6h
- If need urgent decompression, consider bridging with osmotic therapy (see herniation section for further details – call herniation phone)

Hydro- cephalus

Neuro- onc specifics

- Communicating hydrocephalus: common w/ leptomeningeal carcinomatosis
- Noncommunicating hydrocephalus: often from structural lesion obstructing ventricular system Acute tx
- May need EVD/VPS  (page neurosurgery)

Epidural spinal cord compression

Acute tx
- If neurologic deficits or pain associated with compression: immediate treatment with high dose IV dexamethasone (10 mg once, then 4 mg q6h)
- Definitive treatment: surgical decompression (page spine on call) Other
- May require radiation for treatment or palliation

Seizures and status epilepticus

Neuro- onc specifics

- Tend to be focal, but can rapidly generalize
- Risk factors: medication, metabolic derangement, paraneoplastic encephalitis, infection, PRES
- No benefit from seizure prophylaxis

Acute tx
- If status epilepticus: treat as needed as terminating seizure activity may outweigh less immediate risk of drug interaction Other
- See AED toxicities table for further details

Pituitary Apoplexy Acute tx
- Involve endocrinology ASAP
- Supportive measures, hydrocortisone 100 mg IV (prevent adrenal crisis)

PRES

Neuro- onc specifics

- Associated with bevacizumab, sorafenib, cyclophosphamide, l-asparaginase, cisplatin, gemcitabine; immunosuppressants such as tacrolimus and high dose steroids; and consequence of uncontrolled hypertension Acute tx
- Management of blood pressure

Infection risk

Neuro- onc specifics

- Meningitis: often does not have classic triad and without CSF pleocytosis in cancer patients
- Common causative organisms: staph aureus, coag negative staph
- In immunocompromised: also consider fungal (crypto, blastomycosis, histoplasmosis) and parasitic (toxoplasmosis)
- Viral encephalitis more common with immunosuppression: HSV, VZV (consider antibody IgG index testing), CMV, HHV6, WNV, JC virus (PML)
- Pneumocystis jiroveci: at risk due to lymphopenia from TMZ or steroids
- Candida (thrush) common due to immunosuppression
- At risk for cerebral abscess from neurosurgical interventions in context of steroid use

Acute tx
- For meningitis coverage: if in hospital or undergone a neurosurgical procedure, in addition to vancomycin, include cefepime (vs ceftazidime or meropenem) rather than ceftriaxone

Other
- If chronic ALC <500 or chronic steroids: consider daily bactrim SS and acyclovir 400mg daily as prophylaxis

Radiation necrosis

Neuro- onc specifics
- More likely to occur with doses of radiation >50 Gy

Acute tx
- Treatment: Dexamethasone 4-24 mg in divided doses to reduce mass effect Other
- If cannot tolerate steroids, bevacizumab is an alternative

Thrombo- embolic events

Neuro- onc specifics

- High risk for ischemic stroke, pulmonary embolism, DVT, most commonly in postoperative setting and subsequent 6 months
- Hypercoagulable state
- Pro-thrombotic therapies: bevacizumab, sunitinib, sorafenib, cisplatin Acute tx
- Anticoagulation unless contraindication present

Ischemic stroke

Neuro- onc specifics

- Chemotherapy: promotes risk of stroke with immune system compromise – bacterial endocarditis, sepsis, VZV vasculopathy
- Increased risk in cancer population from: hypercoagulable, prothombotic therapies, radiation to head and neck (accelerated atherosclerosis / vasculopathy – can cause moyamoya), tumor emboli from cardiac metastasis, arterial occlusion by tumor, PRES

Acute tx
- IV tPA relatively contraindicated
- Stop bevacizumab
- Otherwise, management per acute ischemic stroke pathway

Intra- parenchymal hemorrhage

Neuro- onc specifics

- Increased risk from chemotherapy, hematologic malignancies (thrombocytopenia, coagulopathy), bevacizumab, radiation vasculopathy, and brain tumors themselves can bleed spontaneously
- Most prone to hemorrhage
- of primary CNS tumors: oligodendroglioma
- of CNS metastases: melanoma, lung, papillary thyroid, renal cell cancer, choriocarcinoma
- high risk hematologic malignancies: APML

Acute tx
- No different than acute IPH management with blood pressure monitoring, consideration of EVD/VPS if evidence of hydrocephalus, or decompression if evidence of herniation

Other
- If suspicious IPH suggestive of underlying CNS neoplasm: repeat MRI 6-12 weeks after initial hemorrhage

Cerebral venous sinus thrombosis

Neuro- onc specifics

- Increased risk from hypercoagulable state, treatment of cancer can lead to severe dehydration, certain medications can trigger thrombosis (tamoxifen, l-asparaginase, heparin (especially if HIT)),  venous compression by extrinsic metastasis, bacterial infection (meningitis or ear infection) Acute tx
- Anticoagulation unless contraindication present

Para- neoplastic syndrome

Neuro- onc specifics

- See paraneoplastic table for details on specific antibodies and related neurologic syndromes

Acute tx

- Immunosuppression: high dose steroids (ie. 1 g IV methylprednisolone for 5 days)
- IVIG 2g/kg divided over 2-5 days
- Plasma exchange

Other
- Treat underlying cancer
- If refractory to acute therapy: consider rituximab, cyclophosphamide, tacrolimus, cyclosporine

Adapted from Lin AL et al. Neurologic Emergencies in the Cancer Patient: Diagnosis and Management. J Intensive Care Med. 2017 Feb; 32(2): 99–115. and Mohile NA. Medical Complications of Brain Tumors. Continuum (Minneap Minn). 2017 Dec;23(6, Neuro-oncology):1635-1652.

