---
title: "Neuroleptic Malignant Syndrome, Serotonin Syndrome, and Acute Dystonia"
category: "Specialty Topics"
section_id: "nms-serotonin-dystonia"
last_updated: "2026-07-01"
source: "UF Neurology Resident Handbook 2026-2027"
---

# Neuroleptic Malignant Syndrome, Serotonin Syndrome, and Acute Dystonia

**NEUROLEPTIC MALIGNANT SYNDROME (NMS)**

**Signs and symptoms**

1. *Mental status change*: agitated delirium, confusion, encephalopathy (82%)

2. *Muscular rigidity*: “lead pipe” tremor (up to 92%) à elevated CPK and myoglobinuric acute renal failure

3. *Hyperthermia*: >38°C (87%), >40°C** **(40%)

4. *Autonomic instability*: tachycardia (88%), labile BP (77%), tachypnea (73%), diaphoresis

**Diagnosis**

1.* Exclude other etiologies: *acute drug intoxication, metabolic derangements, meningitis, etc.

**Treatment**

1. Admit to ICU

2. Discontinue offending agent** **(e.g. neuroleptics, D2 blocking antiemetics or abrupt w/d levodopa)

3. Supportive care for *Autonomic instability*, *DVT/PE prophylaxis*, *IVFs** to prevent** **rhabdo*

4. Symptomatic treatment:

a. *Agitation* - Lorazepam 0.5-1mg prn (may also help with rigidity)

b. *Rigidity* – Dantrolene 0.25-2mg/kg IV q6-12 hours (max dose 10mg/kg/day; be aware of hepatotoxicity)

c. *Fever* – cooling blankets, ice lavage, acetaminophen

**SEROTONIN SYNDROME (SS)**

**S****igns and symptoms**

1**.*** **Mental status change*: agitated delirium, restlessness, disorientation

2.* Neuromuscular hyperreactivi**ty*: tremor, rigidity, myoclonus, rigidity, hyperreflexia (+Babinski and clonus)

3.* **Autonomic instability*: dilated pupils, diaphoresis, hypertension, diarrhea, vomiting

**Diagnosis**

1.* Exclude other etiologies: *acute drug intoxication, metabolic derangements, meningitis, etc.

**T****reatment**

1. Admit to ICU

2.** **Discontinue offending agent (e.g. SSRIs, MAOIs, buspirone, trazodone, lithium, opiates, etc.)

3. Supportive care for *Autonomic instability, DVT/PE prophylaxis*

4. Symptomatic treatment:

	a. *Agitation, Neuromuscular hyperreactivity* - Lorazepam 0.5-1mg prn

b. Cyptoheptadine (*only for severe cases*)** **12 mg PO, then 2mg q2 hours until clinical response

**ACUTE DYSTONIC REACTION**

**Signs and symptoms**

1. *I**ntermittent or sustained dystonic posturing* due to blockade of D2 receptor (neuroleptics, certain antiemetics)

**Diagnosis**

1. *Review medication list*/MAR for offending agent.

2. *Exclude metabolic derangements* (hypomagnesemia, hypocalcemia) or *other drug toxicity*.

**Treatment**

1. Discontinue offending agent

2. Diphenhydramine 25-50mg IV/IM vs Lorazepam 0.5-1mg IV (*acute*); Diphenhydramine 25mg PO qid (*x48hr*)

3. Alternative therapy: Benztropine 2mg IV/IM (*acute*); Benztropine 1-2mg PO bid (*x48hr*)