---
title: "Common Shands and VA Extensions"
category: "Contact Information"
section_id: "shands-va-extensions"
last_updated: "2026-07-01"
source: "UF Neurology Resident Handbook 2026-2027"
---

# Common Shands and VA Extensions

CT east tower: 30508

East tower carotid u/s: 30536

Outpatient radiology scheduling: 50104

North tower echo: 38333

        Echo (weekend+East tower) 733-3667

X-ray tech North tower 44285

X-ray reading room 45544

Body CT Reading room: 45544

Nuc med reading room: 59715

Radiology reading room?: 43964

Nuclear medicine radiology: 46211

9th floor pharmacy: 43399 45608

NT Outpatient pharmacy: 50405

South tower outpatient pharmacy: 30890

East tower inpatient pharmacy: 30539

MICU pharmacist 50069

ID pharmacy: 352-258-5944

AOD 30150

Medicine floors

11-4: 55114

11-5: 51155

10-5: 51050

9-4: 50094

MICU: 50082

Unit 72: 51272

7-4: 50074

7-5: 50075

6-5: 50065

6-4: 50064

ADTU: 50930 ADTU

Select hospital: 50055/50054

Meds to beds: 352-682-8221

Cardiology reading room for MPS 43964

 PICC team 43647 or 43951

50400 - Nutrition

50265 - Dialysis

Heme path: 352-627-2138 (2105)

East tower EEG lab: 2650334

East tower 5th floor EMU reading room 50061

North tower EEG lab: 42200

North tower EEG tech phone: 33882

OnCall dietician 4135431 ***not sure this works

Medical records 42808

Medicine fax number: 352-627-4694

North tower lab - 50412

North tower micro - 50165

Rocky point cytology lab 72121

Send out lab - 40482 (40481)

Mayo clinic account number: C7025954

ID consult 352-294-5481

Thoracic surgery (THO) consult  352-246-5047

Acute pain 352-219-5453

Neurosurgery: 413-2125

Vascular surgery pager: 413-8183

Psychiatry consult: 352-413-1816

Pastoral care (catholic): 3524135264

Pastoral care (non-catholic/protestant): 352-413-5282

Visceral IR pager: 352-413-5512

VASTeam 43647

Wound care: 352-642-6100 (leave message if not there

Telemetry 38601

ED residents:

Core 1: 33089, 33090

Core 2: 33092 (senior res), 33093

Core 3: 33095, 33096, 33097

Trauma Bay: 33099

Fax number to upload medical records to media tab in Epic: 352-627-4371

Zoom Didactic

https://ufl.zoom.us/j/845769745?pwd=TVIvR2dzVjdodnhjUXRjb0JaWU16dz09

Meeting ID: 845 769 745

Passcode: 247 452

Shands wards:

Team rooms/numbers: All door codes are 12354

- Blue: 6502 (x53041)

- Gold: 6534 (x53060)

- Orange: 6434 (x50623)

- Red: 8405 (x44118)

- Green: 7437 (x50256)

| **SHANDS** |  |  |  |  |
| --- | --- | --- | --- | --- |
| Main | 265-0111 |  | MBI Office | 273-5550 |
| Bed control | 5-0233 |  | MBI Fax | 273-5575 |
| Case Manager, Dee | 260-7022 |  | MBI - Jennifer | 273-5549 |
| Case Manager  Wendy | 792-5109 |  |  |  |
| SW 47 Olivette | 494-5275 |  | **VA ** |  |
| On call SW | 413-5241 |  | Main | 376-1611 |
| NCC fellow | 745-1912 |  | VA wrkroom | 5153,5154 |
| CCM charge RN | 494-4023 |  | Bed Control | 6733 |
| NSG | 413-4736 |  | Bed Tower | 548-6000 |
| Neurodiagnostics | 5-0334 |  | Clinic 4C | 4412 |
| EMU | 5-0061 |  | Coumadin Clinic | 7346 |
| ER | 3-0815 |  | CT | 6404, 6585 |
| Unit 56 (Neuro) | 3-0550 |  | Cytology | 6439 |
| Unit 57 (Nsurg) | 3-0551 |  | Echo | 4011 |
| MICU | 5-5114 |  | ER | 6744, 6745 |
| ADTU | 5-0930 |  | EEG Lab | 6552 |
| Unit 46 | 3-0540 |  | Fee Basis | 352-244-5741 |
| Unit 47 (NICU) | 3-0541 |  | GEM | 6839 |
| Neuro Rad | 3-0509 |  | Lab | 6417, 6419 |
| Neuro Rad afterhours | 4-4052 |  | Lab Send Outs | 6437 |
| Angio (OR) | 3-0522 |  | MDSU | 5136 |
| Medicine AOD | 2-8908 |  | Speech Path          5607 |  |
| Core Lab | 5-0412 |  | Telemetry | 5035 |
| Send Out | 40481/82 |  | Neuro Case | pg VA 1424 |
| Neuro PT | 413-2389 |  | manager |  |
| ECHO | 5-0047 |  | OT | 5607 |
| Transfer center | 5-0559 |  | MICU | 6254 |
| Clinic Access Center | 4-5000 |  | MRI | 6870, 6941 |
| **Clinic (Dr. Line)** | **5-7040** |  | Pharmacy | 6591 |
| Clinic Fax | 627-4175 |  | PT | 4127 |
| **MRI East Tower** | **30507** |  | Resident Room | 548-6293, 548- 6294 |
| MRI South Tower | 30857/58 |  | Ward 2D | 6183 |
| MRI North Tower | 45424/50106 |  | Ward 3C | 5142 |
| CT East Tower | 30508 |  | Ward 4A | 5159 |
| CT South Tower | 30895 |  | Ward 4B | 5160 |
| CT North Tower | 46068 |  | VA Neuro Office | 374-6058, 374-6082 |