---
title: "Blood Pressure Pharmacology"
format: html
editor: visual
---

## Blood Pressure Goals

| Situation        | Goal                       | Notes                                                                                                          |
|-----------------------------|--------------|---------------------------------|
| Ischemic stroke  | \<220/120                  | Adjust goals for clinical picture                                                                              |
| s/p tPA          | \<180/105                  | Day 1--2 SBP \<180, Day 3+ SBP \<140 (example)                                                                 |
| s/p thrombectomy | \<180/105 or per attending |                                                                                                                |
| Hemorrhagic      | \<140/105                  | Ultimately goal SBP \<140, but may tolerate slightly higher in perfusion-dependent patient with baseline \>200 |

::: panel-tabset
## ACE Inhibitors

| Agent           | Route | Dose                | Tips / titration                                                                                                                             |
|----------------|----------------|---------------|--------------------------|
| **Lisinopril**  | PO    | 2.5--40 mg QD       | Consider Q12H dosing for additional BP lowering. If renal dysfunction: trial captopril before lisinopril to monitor Cr                       |
| **Captopril**   | PO    | 12.5--150 mg Q8H    | If already using 100 mg Q8H, already exceeds max dose lisinopril, so consider switching over to lisinopril (5:1 ratio) and add another agent |
| **Enalaprilat** | IV    | 1.25--2.5 mg Q3 PRN | PRN for uncontrolled HTN                                                                                                                     |

## Beta Blockers

| Agent          | Route    | Dose             | Tips / titration                                                                                                                                                                                                                                                      |
|----------------|----------------|--------------|--------------------------|
| **Metoprolol** | IV or PO | (type dependent) | Tartrate (IR): Q6H--Q8H<br>Succinate (ER): Q12H --- Cannot give through feeding tube<br>PO → IV conversion is 2.5:1                                                                                                                                                   |
| **Labetalol**  | IV       | 10--60 mg PRN    | 10 mg IV, repeat q15 min until effective, increasing to 20 mg → 40 mg → 60 mg (max bolus dose)<br>Max total dose: 300 mg in 2 hours<br>If IPH & BP \>230/120, skip to 20 mg<br>If unresponsive after 3 doses → nicardipine<br>*IV requires telemetry if on the floor* |
|                | PO       | 100--800 mg Q8H  |                                                                                                                                                                                                                                                                       |
| **Carvedilol** | PO       | 6.25--25 mg Q12H | Has both alpha and beta blocking effects                                                                                                                                                                                                                              |

## Calcium Channel Blockers

| Agent           | Route  | Dose          | Tips / titration                                                                                        |
|-------------------|---------------|--------------|--------------------------|
| **Amlodipine**  | PO     | 2.5--10 mg QD | Best to minimize BP variability: onset gradual in 24--72 hours and reaches steady state in 1--1.5 weeks |
| **Nicardipine** | IV gtt | (titrated)    | Refractory BP, requires ICU. Start 5 mg/hr IV, titrate by 2.5 mg/hr q15 min to max 15 mg/hr             |

## Diuretics

| Agent              | Route | Dose           | Tips                                                                                              |
|------------------|--------------|---------------|--------------------------|
| **Chlorthalidone** | PO    | 12.5--25 mg QD | Twice as potent as HCTZ and longer acting. Can cause hyponatremia and increased Cr (avoid in ICU) |

## Others

| Agent             | Route | Dose            | Tips                                                                                           |
|-------------------|--------------|-----------------|----------------------|
| **Clonidine**     | PO    | 0.1--0.3 mg Q8H | Does **not** increase ICP                                                                      |
| **Nitroprusside** | IV    | (titrated)      | 0.5 mcg/kg/min, max 10 mcg/kg/min. Can increase ICP, but consider if refractory to nicardipine |
| **Hydralazine**   | ---   | ---             | ***AVOID*** due to risk of increased ICP                                                       |
:::

::: callout-tip
## Miscellaneous Tips and Hints

-   **Ibuprofen & ASA**: Ibuprofen should be taken \>8 hrs before or 4 hours after immediate-release ASA as it binds receptors for ASA
-   **SQH**: Delay for 24 hours after tPA, 48 hours after IPH
    -   If weight \<50 kg or low BMI: SQH 5,000 Q12H
    -   If BMI ≥40: enoxaparin 40 mg SQ Q12H
    -   If platelet decrease 50% or greater in few days, consider HIT
-   **Avoid dextrose/glucose** containing IV solutions or standing orders for hypotonic fluids (even if on insulin gtt) in stroke patients
-   **Clopidogrel** activated through P450 2C19: fluoxetine, fluconazole, omeprazole (weak) inhibit formation of active agent
-   **NOACs**: **apixaban** is best choice in stroke patients (least IPH, BID dosing)
    -   Apixaban adjusted dosing: needs to meet 2 out of 3 factors: Age ≥80 y/o, Weight \<60 kg, SCr \>1.5
    -   Apixaban has direct drug interaction with amiodarone, but still reduced rate of stroke and major bleeding vs. warfarin
    -   Not effective in antiphospholipid syndrome or valvular disease
    -   Caution in enzyme inducers/inhibitors or PgP inducers/inhibitors (PHT, CBZ, St. John's wort, rifampin, amiodarone)
:::
