---
title: "Intracerebral Hemorrhage"
format: html
editor: visual
---

## Intraparenchymal hemorrhage causes

-   Hypertension most common etiology -- subcortical/brainstem
-   Cerebral amyloid angiopathy (cortical)
-   Arteriovenous malformation
-   Neoplasm (primary central nervous system, metastatic, leukemia)
-   Hematologic (sickle-cell disease, neoplasm, thrombocytopenia)
-   Moyamoya disease
-   Drug use (warfarin, DOACs, amphetamines, cocaine, phenypropanolamine)
-   Iatrogenic (peri-procedural)

::: callout-important
**ICH Volume = (A × B × C) / 2**

-   **A** = Diameter
-   **B** = Diameter perpendicular to A
-   **C** = Number of slices on CT multiplied by slice thickness in cm
:::

## ICH Score and 30-day Mortality

| Component      | Points |
|----------------|--------|
| **GCS**        |        |
| 3--4           | 2 pts  |
| 5--12          | 1 pt   |
| 13--15         | 0 pts  |
| **ICH volume** |        |
| ≥ 30 cm³       | 1 pt   |
| \< 30 cm³      | 0 pts  |
| **IVH**        |        |
| Yes            | 1 pt   |
| No             | 0 pts  |
| **Location**   |        |
| Infratentorial | 1 pt   |
| Supratentorial | 0 pts  |
| **Age**        |        |
| ≥ 80 yrs       | 1 pt   |
| \< 80 yrs      | 0 pts  |

**30-day mortality**

| Score | Mortality |
|-------|-----------|
| 0     | 0%        |
| 1     | 13%       |
| 2     | 26%       |
| 3     | 72%       |
| 4     | 97%       |
| 5     | 100%      |
| 6     | 100%      |

## Control BP: Goal SBP 100--140

-   Use labetalol 10--20 mg IVP q1h PRN or nicardipine drip (start at 5 mg/h and titrate up as needed). If a nicardipine drip is started, ask ED resident/attending to place arterial line. A PIV can only be used for 24 h.
-   The emergency room is busy. Do not rely on the nurse or ED resident to monitor the blood pressure. The neurology resident must alert the staff if SBP \>140.

## Additional guidelines and workup

-   ABCs, intubation if GCS \<8
-   HOB \> 30°
-   Reverse anticoagulation, if applicable (reversal protocol chart). Hold antithrombotics.
-   Discuss admission disposition with attending/fellow.
    -   Neurology generally admits **intraparenchymal** hemorrhage. Place admission orders to NICU ASAP per FAST protocol; do not wait for neurosurgery consultation.
    -   Subarachnoid hemorrhages go to neurosurgery unless clearly non-aneurysmal.
-   Admit to Vascular Neurology service in Neuro-ICU using **"NEURO Stroke ICH Admission"** order set
-   On admission, place SCD for DVT prophylaxis. Re-start heparin/LMWH after 24 h or stable repeat imaging (discuss with attending).
-   MRI brain (with/without contrast) unless obvious hypertensive etiology
-   CTA head vs. MRA head vs. conventional angiogram (unless hypertensive) -- discuss with attending/fellow
-   Consider CTH stability scan within 6 hours
-   Consider UDS, also blood cultures/TEE if concern for endocarditis

::: callout-tip
## Subarachnoid hemorrhage causes

[Basilar cisterns:]{.underline} cerebral aneurysm until proven otherwise, differential includes trauma, other vascular malformations

[Isolated high convexity:]{.underline} trauma, cerebral amyloid angiopathy, RCVS
:::
