---
title: "Movement Examination"
category: "Neurological Exam"
date-modified: today
author: Luis Silva
format:: html
---

## Coordination

**Ataxia** --- incoordination of movement rhythm through time and space, irrespective of the final target.

**Dysmetria** --- subtype of ataxia: imprecision of targeting movements (over- or under-shooting).

### Midline (Vermal) Signs

-   Trunk ataxia
-   Optic ataxia
-   Ataxic dysarthria (scanning speech)
-   Nystagmus

### Hemispheric (Appendicular) Signs

-   Finger-to-nose (FTN)
-   Heel-to-shin (HTS)
-   Rapid alternating movements (RAM) --- **dysdiadochokinesia**

## Movement Examination

### Bradykinesia/Hypokinesia

Decrements in speed/amplitude of movement with repetition.\
Test with:

-   Finger Tapping
-   Fist ope/close
-   Toe Tapping

### Hyperkinetic Movements

-   **Tremor**: slow, oscillatory movements with regular interval

    -   **Resting tremor**: arms relaxed in lap or over chair arms
    -   **Action tremor** (postural/kinetic)
        -   Egocentric: reaching toward face
        -   Allocentric: reaching outward
    -   **Dystonic tremor**: find null point by rotating posture

-   **Dystonia** --- sustained muscle engagement, irregular

-   **Myoclonus** --- brief, irregular, jerky movements in **one plane** of space; not suppressible

    -   **Positive myoclonus**: in plane of muscle contraction
    -   **Negative myoclonus**: loss of tone (e.g., asterixis)

-   **Chorea** --- multiplanar, semi-brief, irregular, rhythmic movements (complex myoclonus can mimic, look for multiplanar movements)

-   **Hemiballismus** --- large amplitude, irregular

-   **Tics** --- irregular, jerky movements (simple or multiplanar, vocalizations) with **URGE** followed by relief; **suppressible**

-   **Stereotypies** --- irregular, complex, **fixed/repetitive** movements without clear urge; often triggered by negative emotional states
