---
title: "Neuro-oncology Complications and Emergencies"
---

Neuro-oncology Emergencies
Common Medical Brain tumor Iatrogenic causes
Complications of Brain
Tumors Direct effects Indirect effects Antineoplastic therapies Supportive therapies
•
•
E
St
p
r
i
o
l
k
ep
e
sy •
•
V
St
T
ro
E
ke
• • • S D i B s n y I e i s A m a h i b p D a p e i v t d H t o i e u o m s s r a s l • • Sur S C a g b t e e r s r o r c e y k e b e s r s al • • • • • • • Ch N v C H S P B p M em o e t R o o T a r y r m w o n u E o f N e o k s s t i l S e h t e t o r e i l i a a e t p n o t , r a g i a x o t p i i n o c y i n ty • • • • • Rad F D M H C i a a e e a e t t r a t i m a i m g r o r i u o a n n a e r c g t y i t t s l i l o s o s s s s • • • • • • Ste C s I D m M d M T r n y o i r u i e s f o y n e i a s o e l d m o o d b l h c r s i d p r e d i t t o o n i u a t e o r e m t g s r h n s e y • • • • • • • AE S F I H T R M D r e a r a r y y e s d t i s p i t m e h a g a o l t b u o o n io i e t r a l o n i t t x r y e ic m it i y a
ssam ecuder ot s y e G so d 0 5 d > ed n iv o i i d ta n id i a g r m f o 4 2 se -4 so e d n o h s ti a w h t r e u m cc a o xe o D t y :t l n ek e i m l e ta ro er M T • • sc - i o f r ic u c e e n p N o s no s i i t s a o i r d c a e R n
y y p sp a r o o e i t b h s t d f c o n it o o d p l m e s i e s y o r e  r s e a d e y r is t c i n e li o d b c a n e , a a m c m r e e o n p h o p r s a m a l h u y t c l e s S m a N v a x C s e e d s ro a s e f a r s c y u n s o i p i r c o o i i p m b s u t u n t s e : d g a n m ru a e o n d t o e i e c s g e in d l s e i d w r g b i e o o n a r s e a s V f t a s I
• •
sc - i o f r ic u c e e n p N o s
tceffe xt etucA
DIB gm 4 yllacipyt :enosahtemaxed fo esod evitceffe tsewol esU
•
evitanretla na si bamuzicaveb ,sdiorets etarelot tonnac fI • rehtO
fo nruter esuac ton seod taht esod tsewol ot repat ot tpmetta–tneiciffus
xt etucA
tceffe ssaM
noitcnuf riapmi taht sticifed evitnatsbus
nitalp t s s i o c m s , h b t i ,T n n o e V f m D ar o 6 ,m s t n , s b e i i l u n o q i b t e i m n sb u e u s y s , r b a d a n n m o a m u g z n l i u c it p a t v e ,e e s k b e o v : r s it t e a s i r p c e e a i t p m r a e o t e h s ts h t e o c c l p s b i i t a o n r lu o b i g f m y a l k n o o s o r c ir h m r e t h - m p g o y i o r H H P c • • • sc - i o f r ic u c e e n p N o s -o b c m i s lo t o n b r e m h v T e e
r c e in vo eg a o m sa e v d e tn e a v c o if r i p n m gi i s n h a t c iw s a s r m om re u a t i t g n g n m n o o i l c s b n n a a i m h d n u io e z v i t c a s a a o v r t t e n b m o m p c e o 2 g r d f r a n t l i a f . e e m n i( e a s b s t 6 k n y e t e a a e i m t w e a l p ) u o a d t t m c e s e h e y l d a e c d S S e
• •
rehtO
tneserp noitacidniartnoc sselnu noitalugaocitnA • xt etucA
h6q gm 4 neht ,ecno VI gm 01 enosahtemaxeD :noitainreh ro dednutbo fI
•
metsys enummi htiw ekorts fo ksir setomorp :yparehtomehC •
ees(ypareht citomso htiw gnigdirb redisnoc ,noisserpmoced tnegru deen fI
•
xt etucA
noitainreH
ilobm d e y e h r t o t a a m r p e S ,e u o l E e l t l b c u R , a c ) c P l a a s u ( y a g , o v r k a o m c o V m e c a n Z r u y e o V t d p m n y y , b a s h i e s d n : s p m a o u e e a i o s s h c u r , f o s n l c i n t a t c i c o n o d i o – r t l a a i a t y c l i a u h r o i e p d t d t a o a n r p r a p e o , , s r l l s a u e e is i c i c r p a n s e t a a t a s r v c c a e a t / h n b e t m i s – c k i s i s c e t o i a o s r r i i b e d m d l m r c e o a s s o c r o a p h e r m m t e r o c h o o n r t r p c a I f • sc - i o f r ic u c e e n p N o s cim e e k h o c r s ts I
s g is n o it t c a u m rt o s n b i o c r n ac o i l s a e e l g l n ar in u e tc m u ) o r en t t s p o h m e p l o / n r o w f it a n n i e n o t r m f e o h m : l s l o a u c c la – : h s u s p l l i e a a c h t o e p d r e d r c e y h o h t r r d g u y n f m h r it o a e f g c t n n s i o n i y t i u t s a c c m e r s i a n m n l u u o o m c it i c a r m n i t n n o o r e N e C v h
• •
sc - i o f r ic u c e e n p N o s
su - l o a r h d p y e H c
detacidniartnoc ylevitalerAPt VI •
)yregrusoruen egap( SPV/DVE deen yaM
•
xt etucA
bamuzicaveb potS • xt etucA
,yhtapolucs
a s v e y i n c a n o w a i h t n a t g i a d i p l a a r m e k ,b o c a r i m g ts o u l c z o i i m t c a a e m v h e e c b h s i , , ) y e y p t h u a t c r a e a p h r o t e o l p u m g t a n e o h e c m c , m e ai g n o a e r n f p a k o m s ty i r , c e o d si e b w s m a r e e o r h r c h t n O t I ( • •
)h6q e g ta m id 4 em n m e )l h l i a t c :n ,e n o c o i n s e o n se i p g r s p m e m g a 0 n o p 1 o c ( ( i n t h e a o t n i i l i o w l s a s s p a e d h r e r p t o t e a m m i t c n o o a e c x s m e s e d a d t a l n a e V i c r a I t i p g r e r o s r u o o f s d n s : t t o h n ic i g e t i a i f m h e id d t h a a r t c e i i r w e g t r o e i t u l v n o q i e r t e m i u n r e t i y n f a a e e M D f r I t
• • •
xt r e e tu h c tO A
n o d i r s o l s a c e r r u l p a d m n ip i o p E c s
llec
laner ,dioryht y y l r s a a u m ll o i o p e i a n l p g a o t , n g rd o n n p u e s l d , d a o e m g e i o l l b o n a n : a s l a e m r c o m o m s e n : e s u v i g e c l t e s a r S a a s h m N t c r s o r a e C o i t h r e m o y t m h r e s a c h r S m o , N o r m i e t r C c p u e n t n f f a n o o o c i r a p r • • b ts d o n M a • sc - i o f r ic u c e e n p N o s lamyhcn -a e r r t a n p I
,sitilahpecne citsalpoenarap ,tneme e g z n il a a r r e e d n s e i c x g i a l o l y y b l h d a p i t p e o a m r r p n , e n a r o c u i t z t u a ie c b s i d , m l e S a m E c o o r R : f f s P t r e i o b f ,n t e c o n o a t e i f t b d c k n e o s f e i N n R T i
• • •
sc - i o f r ic u c e e n p N o s
dna se r s u u z t i a e t S s
erusserp doo L l M b P ht A iw :s t e n ic e n m a e n g g a il n a a m m c H ig P ol I o e t t a u m c e a h n k ah si t r t h n g e i r h effi • d oN • egahrromeh
yam ytivitca eruzies gn n it o a i n t i c m ar r e e t t n s i a g u de rd d e f e o n k s s a i r t a e e t r a t id :s e u m c m itp i e s l s i e p l e h s g u i t e a w ts t u f o I
•
xt etucA
sucitpelipe
,sulahpecordyh
fo ecnedive fi SPV/DVE fo noitaredisnoc ,gnirotinom xt etucA
sliated rehtruf rof elbat seiticixot DEA eeS
•
rehtO
IRM
taeper :msalpoen SNC n g o n i i t y a l i r n e r d e n e h g u a f h o fo r e r e o c v n m i e t e s d h e iv g l e g a u it f s i i n H n i o r P e is I t s f s e a u r s p o k m i e c e i o p w c s e u 2 d s 1 r - f o 6 I • rehtO
)sisirc lanerda tneverp( VI gm 001 enositro P c A or S d A y h y g ,s o e l r o u n s i a r e c m od e n v e i t e r v o l p o p v u n S I
• •
xt etucA
y y x r e a l t p iu op ti A P
,esanigarapsa-l ,edimahpsohpolcyc ,binefaros ,bamuzicaveb htiw detaicossA
•
-orueN
dael
nac recnac fo tnemtaert ,etats elbalugaocrepyh morf ksir desaercnI •
esod hgih dna sumilorcat sa hcus stnasserppusonummi ;enibaticmeg ,nitalpsic
cno
si s s o u b o m ne o v r h , t ) ) r T eg IH gir t f i n y a l c la i s c n e o p i s ta e c ( i n d i e r m ap n eh ia t ,e re sa c n , i n g o a i r t a a p rd sa y - h l e , d n e e f r ix ev o e m s a o t t ( -oru c e n N o suni s la s r u b o er n e e C v
noisnetrepyh dellortnocn e u r u f s o s e e r c p n e d u o q o e lb sn f o o c t d n n e a m ; e sd ga io n r a e M ts
•
s x c t i f e i t c u e c p A s
SERP
rae
ro sitigninem( noitcefni lairetcab ,sisatsatem cisnirtxe yb noi ) s n se o r i p tc m ef o n c i scificeps sisobmorht
ni sisotycoelp FSC tuohtiw dna dairt cissalc evah ton seod netfo :sitignineM
•
tneserp noitacidniartnoc sselnu noitalugaocitnA • xt etucA
stneitap recnac hpats evitagengaoc ,suerua hpats :smsinagro evitasuac nommoC •
detaler dna seidobitna cificeps no sliated rof elb se a m t c o i r ts d a n lp ys o e c n ig a o r l a o p r u e e e n S • -oru c e n N o
,sisocymotsalb ,otpyrc( la ) g s n is u o f m re s d al i p sn o o xo c t o ( s c l i a t i : s d a e r s a i p m d o n r a p m )s o is c o o m n s u a m lp m ot i s n ih I •
-orueN
scificeps
VZV ,VSH :noisserppusonummi htiw nommoc erom sitilahpecne lariV
•
cno
)s s y d ad io 5 re s r t o y s a f e d s e o n 5 d o -2 l h o r g s e i i v h n o d : n e d r o e p i d s l e y i s v g h e i n r t d e p a m p h gk c u x V / s e o g I n 2 a g u m G m 1 s I a . m V e lP i I I ( • • • xt etucA c e i m ts o al r - p d a o n ra e y P n s
) L fo M s d t P x io ( e r t s e n u t o r s i c v r o n C i Z J s M n ,V o T N it n W m n e o o v , i 6 r r s f e V s t a e n H i r n i p H e l p a p c u , o V i s g h o M r p n u C m u so m y , r ) l u m g o e n i t n i t o e s m t u e d e t o u x r k d f e s d s i n r s n o e t i c a m G s : b m i g c a I e o v l c y a o d r ) r b o h i e j b s r u s i e t i r t n c h s a y r t ( o c r o e a f d d m k i i s s d u i n n r e o n a t c A C P (
• • •
scificeps
noitce k f s n i I r
recnac gniylrednu taerT •
esu diorets
,edimahpsohpolcyc ,bamixutir redisnoc :ypareht etuca ot yrotcarfer fI • rehtO
lacigrusoruen a enogrednu ro latipsoh ni fi :egarevoc sitigninem roF
•
eniropsolcyc ,sumilorcat
ro emidizatfec sv( emipefec edulcni ,nicymocnav ot noitidda ni ,erudecorp
xt etucA
;be . F 25 7 6 1 1 0 -5 2 3 . 6 d 1 eM :)y g e o ra lo C cn e o v -o is r n u e e t N nI , J 6 . ( t 3 n 2 em ;ce e D ga n 7 a 1 M 02 d n .) a n n s i is M ong p a a i e D nn : i t M ne ( i t m aP u u r n ec i n tn a o C C e . h sr t o n m i u se T ic n n e i g a r r e B m f E o s c n ig o o it lo a r c u il e p N m o . C la l t a e c L id A eM n . i A L .5 N 1 m 1 o – e r l f 9 i h d 9 o e M t : p )2 a d ( d 2 n A 3 a
dna SSmirtcab yliad redisnoc :sdior s e e i t n x s o a c l x y i a n h i o r p t r o f h e r c c p r n s o a a h 0 y t 0 l i r 5 a e d < h g t C a m r L 0 ) A m 0 4 c e i n r n i e v o p o r o h lc r c y e c m f a I
•
rehtO

