---
title: "Seizure Consult"
format: html
editor: visual
---

# HISTORY:

## New onset seizure or known epilepsy?

**If known epilepsy**: goal is to determine ASM regimen and compliance, seizure type/frequency and last seizure, epilepsy physician, any recent triggers (see below). Check ASM levels and if low or they are non-compliant, re-load; if not, consider increasing ASM dose. Ask about prior ASMs tried.

**If new onset seizures**, obtain comprehensive first seizure history:

• RISK FACTORS: history of febrile seizures, family history of seizures, prenatal and perinatal complications, developmental delay, history of head trauma, history of CNS infection, history of CNS mass/malformation, metabolic disorder, stroke (hemorrhagic\>ischemic), drug/alcohol use, consanguinity.

• TRIGGERS LOWERING SEIZURE THRESHOLD: Medications, ASM noncompliance, infection, metabolic abnormalities, toxic ingestion, menses, stress, sleep deprivation, EtOH/benzo withdrawal, fever, use of stimulants, hypoglycemia, electrolyte disturbance, hypoxia, acute medical/neuro illness.

• CHARACTERISTICS: aura (visual, auditory, olfactory, epigastric rising sensation, psychic (déjà vu, derealization, depersonalization, fear, anxiety), type of seizure (especially how its starts), eyes open or closed, lateral eye or head deviation, length of seizure, associated tongue bite or other injury, incontinence, post-ictal confusion, post-ictal weakness. Start by asking if they can tell when they will have a seizure.

• SUBTLE SEIZURE SIGNS: history of staring, automatisms, waking up incontinent or injured (tongue bite), myoclonic jerks. May or may not discriminate between epileptic vs. other events. History of injury during events.

## EXAM:

Focus on mental status, post-ictal paralysis or other focal deficits, subtle signs of ongoing seizures such as abnormal movements, head or eye deviation/version, eyelid twitching, pupillary abnormalities or hippus; tongue bite/other injury, and meningeal signs

## ED WORKUP:

ASM levels (only carbamazepine, phenytoin, valproate and phenobarb levels are available acutely, but others can be helpful to establish compliance), non-contrast head CT (new seizures only!), can consider MRI with/without contrast (seizure protocol). Basic labs including electrolytes and CBC, infectious workup (UA, CXR), toxicology screen, LP if concern for meningitis.

SEE ALOGIRTHMS IN DRIVE OR PRINTED IN TEAM ROOM.

::: callout-warning
[**Not Returning to Baseline after a Seizure?**]{.underline}

The two most common reasons patients don't wake up are prolonged post-ictal periods and overly eager benzo administration ... But don't miss anything important:

·    Make sure the patient isn't still seizing. Look for subtle abnormal limb or eye movement, fluctuating awareness, or complete lack of improvement. Even though convulsive seizures may be controlled, up to 40% of patients in status may continue having subclinical seizures. Consider a stat EEG.

·    Get a head CT if you don't have one yet.

·    Consider LP if you have any concern for meningitis/encephalitis or SAH not seen on head CT.

·    You may need to admit a patient overnight for prolonged postictal period or benzo intoxication or if there is no clear medical reason for seizure (e.g., EtOH w/d, infection).
:::

# PLAN:

• ASM: load and then start maintenance dose (do not start ASMs for an uncomplicated first seizure)

• Prescription assistance forms available at NeedyMeds.org; pricing at GoodRx.

• EEG: highest yield within 24-48 h. If the patient is not "back to baseline," consider stat EEG.

• MRI with and without contrast seizure protocol, if warranted

• Ativan IV PRN seizure activity

• Evaluate medication list for medications that lower the seizure threshold.

• Can discharge from the ED if they only had 1-2 seizures, have returned to baseline, and have nothing in the above workup requiring admission.

• Inform patient that he/she cannot drive for ≥ 6 months per Florida state law. Document!

• Refer to the Urgent Clinic follow-up or your continuity clinic via Epic. Do not refer to Epilepsy Clinic without reviewing with Epilepsy attending first.
