---
title: "IV DHE Protocol"
format: html
editor: visual
---

Dihydroergotamine (DHE) is a serotonin agonist with neurologic effects. It is also a venoconstrictor; those with difficult IV access may require PICC line. DHE can be used to treat refractory migraine or cluster headache.

::: callout-important
Counsel patient that when DHE protocol is complete that unfortunately there are no other inpatient therapies and discharge will occur even if headache hasn’t improved.
:::

## Contraindications

-   Peripheral vascular disease
-   CAD
-   Stroke
-   Severe or poorly controlled HTN
-   Liver or renal impairment
-   Pregnancy
-   Triptan use within 24 hours

# PROTOCOL

1.  Admit to Neurology/telemetry floor bed, START IVF NS \@ 75 cc/hr; continue home preventative agents
2.  Baseline EKG, weight, CBC, CMP, Mag, Phos, pregnancy urine screen
3.  Give one-time Depakote 500 mg and Dexamethasone 8 mg PO
4.  Order DHE 0.5 mg IV ×1, followed by 0.5–1 mg q8h (9–10 doses)
5.  Premedicate with Benadryl 25 mg IV + Phenergan 25 mg IV
6.  Measure vitals before each infusion. Hold if SBP \> 170 or DBP \> 100
7.  Can slow rate of infusion per patient preference
8.  Monitor for common side effects: chest pain (stop infusion, EKG, trops), GI symptoms, diarrhea
9.  Can order scheduled IV Mag 2 g qd, Toradol 15–30 mg q8h prn for breakthrough pain

::: callout-note
If headache has completely resolved, treat for an additional 3 doses and then consider early discontinuation.
:::
